#spring:
#  profiles:
#    active: "dev"

spring:
  data:
    mongodb:
      uri: mongodb+srv://epst-brevets:INCREDIBLEble$$ing2@mymdb.ar0qt.mongodb.net/epst-brevets?retryWrites=true&w=majority
server:
  port: 8081

