version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - sgc-service/target/sgc-service.jar
  name: sgc-service.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
    - maven